resources:
- repo: self
queue:
  name: Hosted Linux Preview
steps:
- task: Docker@0
  displayName: Build an image
  inputs:
    azureSubscription: 'Microsoft Azure Enterprise'
    azureContainerRegistry: '{"loginServer":"benaksdemob75b.azurecr.io", "id" : "/subscriptions/c39e4605-fe9c-4bda-a716-739102ebd6ee/resourceGroups/benaksdemoa448/providers/Microsoft.ContainerRegistry/registries/benaksdemob75b"}'
    dockerFile: Dockerfile
    buildArguments: 'VCS_REF=$(Build.SourceVersion)'
    includeLatestTag: true

- task: Docker@0
  displayName: Push an image
  inputs:
    azureSubscription: 'Microsoft Azure Enterprise'
    azureContainerRegistry: '{"loginServer":"benaksdemob75b.azurecr.io", "id" : "/subscriptions/c39e4605-fe9c-4bda-a716-739102ebd6ee/resourceGroups/benaksdemoa448/providers/Microsoft.ContainerRegistry/registries/benaksdemob75b"}'
    action: 'Push an image'
    includeLatestTag: true

- task: HelmInstaller@0
  displayName: Install Helm 2.9.1
  inputs:
    helmVersion: 2.9.1

- task: HelmDeploy@0
  displayName: helm init --client-only
  inputs:
    azureSubscription: 'c39e4605-fe9c-4bda-a716-739102ebd6ee'
    azureResourceGroup: benaksdemoa448
    kubernetesCluster: ben-aks-demo
    command: init
    upgradeTiller: false
    arguments: '--client-only'

- task: HelmDeploy@0
  displayName: helm package
  inputs:
    azureSubscription: 'c39e4605-fe9c-4bda-a716-739102ebd6ee'
    azureResourceGroup: benaksdemoa448
    kubernetesCluster: ben-aks-demo
    command: package
    chartPath: 'charts/croc-hunter'

- task: PublishBuildArtifacts@1
  displayName: drop
