FROM golang:1.14.2-alpine3.11 as builder

RUN apk update && apk add --no-cache git

WORKDIR $GOPATH/src/croc-hunter/

ENV GOPATH /go

COPY croc-hunter.go /go/src/croc-hunter/
COPY static/ static/

RUN go get -d -v

RUN go build -o /go/bin/croc-hunter

FROM alpine AS final

USER 1000

WORKDIR /app

COPY static/ static/ 

COPY --from=builder /go/bin/croc-hunter /app/croc-hunter

EXPOSE 8080

CMD ["/app/croc-hunter"]
